# Generated by Django 6.0.5 on 2026-05-21 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('game', models.CharField(choices=[('fortnite', 'Fortnite'), ('codm', 'Call of Duty Mobile'), ('mk', 'Mortal Kombat'), ('fc', 'EA Sports FC'), ('apex', 'Apex Legends')], max_length=20)),
                ('game_mode', models.CharField(blank=True, max_length=100)),
                ('format', models.CharField(choices=[('single_elim', 'Single Elimination'), ('double_elim', 'Double Elimination'), ('league', 'League / Round Robin')], default='single_elim', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open - Registering'), ('closed', 'Registration Closed'), ('live', 'Live'), ('complete', 'Complete')], default='open', max_length=20)),
                ('max_players', models.IntegerField(default=16)),
                ('prize_pool', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('prize_currency', models.CharField(default='ZMW', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('rules', models.TextField(blank=True)),
                ('discord_link', models.URLField(blank=True)),
                ('best_of', models.IntegerField(default=3)),
                ('finals_best_of', models.IntegerField(default=5)),
                ('start_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bracket_generated', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed', models.IntegerField(blank=True, null=True)),
                ('game_tag', models.CharField(max_length=80)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('checked_in', models.BooleanField(default=False)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to=settings.AUTH_USER_MODEL)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='tournaments.tournament')),
            ],
            options={
                'unique_together': {('tournament', 'player')},
            },
        ),
        migrations.CreateModel(
            name='Bracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_rounds', models.IntegerField(default=0)),
                ('size', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tournament', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bracket', to='tournaments.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField()),
                ('match_number', models.IntegerField()),
                ('score_p1', models.IntegerField(default=0)),
                ('score_p2', models.IntegerField(default=0)),
                ('best_of', models.IntegerField(default=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('live', 'Live'), ('complete', 'Complete'), ('bye', 'Bye (auto-advance)')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('played_at', models.DateTimeField(blank=True, null=True)),
                ('next_slot', models.IntegerField(default=1)),
                ('bracket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournaments.bracket')),
                ('next_match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fed_by', to='tournaments.match')),
                ('player1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p1_matches', to='tournaments.registration')),
                ('player2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p2_matches', to='tournaments.registration')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_matches', to='tournaments.registration')),
            ],
            options={
                'ordering': ['round_number', 'match_number'],
                'unique_together': {('bracket', 'round_number', 'match_number')},
            },
        ),
    ]
